version: '3.8'

services:
  server:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:4.4-ubuntu2004
    ports: 
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
